server:
  port: 8471
logging:
  file: /java/C2S_LOGS/fis/fis.log
info:
  component: FHIR integration service
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ReadTimeout: 50000
c2s:
  fis:
    fhir:
      publish:
        serverUrl:
          resource: http://localhost:8469
        # configure only patient resource different with reource url
          patient: http://localhost:8470
        clientSocketTimeoutInMs: 768000
        use-create-for-update: false
        encoding: json