server:
  port: 8471
logging:
  file: /java/C2S_LOGS/fis/fis.log
info:
  component: FHIR integration service
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ReadTimeout: 50000
c2s:
  fis:
    ssn:
      codeSystem: http://hl7.org/fhir/sid/us-ssn
      codeSystemOID: urn:oid:2.16.840.1.113883.4.1
    mrn:
      codeSystem: https://bhits.github.io/consent2share/
      codeSystemOID: 1.3.6.1.4.1.21367.13.20.200
    fhir:
      publish:
        enabled: false
        # configure fhir server base url
        serverUrl:
          resource: http://localhost:8469
        # configure only patient resource different with reource url
          patient: http://localhost:8470
        clientSocketTimeoutInMs: 768000
        use-create-for-update: false
        encoding: json
